// Generated by CoffeeScript 1.9.3
(function() {
  var errHandler;

  exports.err404 = function(req, res, next) {
    var err;
    err = new Error('Not Found');
    err.status = 404;
    return next(err);
  };

  exports.devErrHandler = errHandler(function(_) {
    return _;
  });

  exports.prodErrHandler = errHandler(function(_) {
    return {};
  });

  errHandler = function(errGetter) {
    return function(err, req, res, next) {
      res.status = err.status || 500;
      return res.render('error', {
        message: err.message,
        error: errGetter(err)
      });
    };
  };

}).call(this);

//# sourceMappingURL=predef.js.map
