// Generated by CoffeeScript 1.9.2
(function() {
  var errHandler;

  exports.err404 = function(req, res, next) {
    var err;
    err = new Error('Not Found');
    err.status = 404;
    return next(err);
  };

  exports.devErrHandler = function(err, req, res, next) {
    res.status(err.status || 500);
    return res.render('error', {
      message: err.message,
      error: err
    });
  };

  exports.prodErrHandler = function(err, req, res, next) {
    res.status(err.status || 500);
    return res.render('error', {
      message: err.message,
      error: {}
    });
  };

  errHandler = function(errGetter) {};

}).call(this);

//# sourceMappingURL=predef.js.map
