// Generated by CoffeeScript 1.9.3
(function() {
  var app, bodyParser, cookieParser, debug, express, http, logger, predef, props, route, server, stylus;

  express = require('express');

  logger = require('morgan');

  cookieParser = require('cookie-parser');

  bodyParser = require('body-parser');

  stylus = require('stylus');

  app = express();

  props = require('./server/lib/config/properties')(__dirname);

  route = require('./server/lib/config/routes')(app);

  predef = require('./server/lib/config/predef');

  debug = require('debug')('andor:server');

  http = require('http');

  app.set('views', props.client.views);

  app.set('view engine', 'jade');

  app.use(logger('dev'));

  app.use(bodyParser.json());

  app.use(bodyParser.urlencoded({
    extended: false
  }));

  app.use(cookieParser());

  app.use(stylus.middleware(props.client.root));

  app.use(express["static"](props.client.root));

  route('/', 'index');

  route('/users', 'users');

  app.use(predef.err404);

  if (app.get('env' === 'development')) {
    app.use(predef.devErrHandler);
  }

  app.use(predef.prodErrHandler);

  app.set('port', predef.normalizePort(process.env.PORT || '3000'));

  server = http.createServer(app);

  server.listen(app.get('port'));

  server.on('error', predef.serverOnError(app));

  server.on('listening', predef.serverOnListening(server, debug));

}).call(this);

//# sourceMappingURL=config.js.map
