// Generated by CoffeeScript 1.9.3
(function() {
  require('../lib/routes/route')(module)(function(router, route, view) {
    return route('/', view('index', {
      title: "Express"
    }));
  });

}).call(this);

//# sourceMappingURL=index.js.map
