// Generated by CoffeeScript 1.9.2
(function() {
  require('../lib/routes/route')(module)(function(router, route, arg) {
    var view;
    view = arg.view;
    return route('/', view('index', {
      title: "Express"
    }));
  });

}).call(this);

//# sourceMappingURL=index.js.map
