// Generated by CoffeeScript 1.9.2
(function() {
  require('../lib/routes/route')(module)(function(router, route, arg) {
    var raw, view;
    view = arg.view, raw = arg.raw;
    return route('/', raw('respond with a resource'));
  });

}).call(this);

//# sourceMappingURL=users.js.map
